apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: second-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    # - protocol: TCP
    #   port: 443
    #   targetPort: 8443
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-app
          image: anarkia1985/kub-first-app:2
  selector:
    matchLabels:
      app: second-app
