apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    group: example
spec:
  selector:
    app: second-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    # - protocol: TCP
    #   port: 443
    #   targetPort: 8443
  type: LoadBalancer
